# Generated by Django 4.0 on 2021-12-22 21:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Амплуа')),
            ],
        ),
        migrations.CreateModel(
            name='Chart_Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('opponent', models.CharField(max_length=100, null=True, verbose_name='Соперник')),
                ('area', models.BooleanField(default=False, null=True, verbose_name='Домашняя игра')),
                ('score', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Формат: 0:0', regex='\\d+:\\d+')], verbose_name='Счёт')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('citizenship', models.CharField(max_length=100, null=True, verbose_name='Гражданство')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bd_team.category_player', verbose_name='Амплуа')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_game', models.IntegerField(default=0, verbose_name='Кол-во игр')),
                ('count_washers', models.IntegerField(default=0, verbose_name='Кол-во шайб')),
                ('indicator', models.IntegerField(default=0, verbose_name='Показатель')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_team.player', verbose_name='Игрок')),
            ],
        ),
    ]
