# Generated by Django 4.0 on 2021-12-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardplayer',
            name='image',
            field=models.ImageField(null=True, upload_to='image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='boardplayer',
            name='biog',
            field=models.TextField(null=True, verbose_name='Отображаемая информация'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
