# Generated by Django 4.0 on 2021-12-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slug',
        ),
        migrations.AddField(
            model_name='player',
            name='base',
            field=models.BooleanField(default=False, verbose_name='Основа'),
        ),
    ]
