# Generated by Django 4.0 on 2021-12-24 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0002_status_chart_games_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart_games',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='chart_games',
            name='score',
            field=models.CharField(max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Формат: 0:0', regex='\\d+:\\d+')], verbose_name='Счёт'),
        ),
    ]
