# Generated by Django 4.0 on 2021-12-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0002_remove_player_slug_player_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['number']},
        ),
    ]
