# Generated by Django 4.0 on 2021-12-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0002_boardplayer_image_alter_boardplayer_biog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='biog',
            field=models.TextField(null=True, verbose_name='Отображаемая информация'),
        ),
        migrations.AddField(
            model_name='player',
            name='indicator',
            field=models.IntegerField(default=0, verbose_name='Показатель'),
        ),
        migrations.DeleteModel(
            name='BoardPlayer',
        ),
    ]
