# Generated by Django 4.0 on 2021-12-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0003_alter_chart_games_options_alter_chart_games_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_games',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bd_team.status', verbose_name='Статус игры'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
