# Generated by Django 4.0 on 2021-12-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0003_alter_player_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart_Games',
            new_name='Game',
        ),
    ]
