# Generated by Django 4.0 on 2022-01-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0004_player_public_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='count_cup',
            field=models.IntegerField(default=0, verbose_name='Количество кубков'),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(null=True, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='player',
            name='biog',
            field=models.TextField(blank=True, null=True, verbose_name='Отображаемая информация'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Номер'),
        ),
    ]
