# Generated by Django 4.0 on 2021-12-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0005_game_judge_alter_game_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Game_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_washers', models.IntegerField(default=0, verbose_name='Кол-во шайб')),
                ('yellow_card', models.IntegerField(default=0, verbose_name='Жёлтая карточка')),
                ('read_card', models.IntegerField(default=0, verbose_name='Красная карточка')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Player_Rating',
        ),
        migrations.AddField(
            model_name='player_game_status',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_team.game'),
        ),
        migrations.AddField(
            model_name='player_game_status',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_team.player'),
        ),
    ]
