# Generated by Django 4.0 on 2021-12-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0006_player_game_status_game_archive_delete_player_rating_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Game_Status',
            new_name='Player_Game',
        ),
    ]
