# Generated by Django 4.0 on 2021-12-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bd_team', '0007_rename_player_game_status_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd_team.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='player_game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_team.player', verbose_name='Игрок'),
        ),
        migrations.AlterUniqueTogether(
            name='player_game',
            unique_together={('player', 'game')},
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
