# Generated by Django 4.0 on 2021-12-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_team', '0008_alter_game_archive_alter_player_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
